### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by VictorChow** [Loren1994/AndroidUpdate#3]
如果已经安装了一个使用AndroidUpdate的应用，再安装一个使用AndroidUpdate的应用时就报错。
Can't install because provider name pers.loren.appupdate.fileprovider is already used.

**Comment by Loren1994** [comment]
can u speak Chinese?

**Comment by VictorChow** [comment]
如果已经安装了一个使用安卓更新的应用，再安装一个使用安卓更新的应用时就报错。
无法安装珀耳斯.劳伦.应用程序更新.文件提供者因为供应商名称已被使用。

**Comment by Loren1994** [comment]
update version 1.1.4
