### ISSUE TITLE
强制更新没反应

### ISSUE THREAD

**Issue by qq237398825** [Loren1994/AndroidUpdate#4]
我在iPad (android版本是5.1)上测试强制更新，不起作用。一直停留在0%，且0%这两个字看不全。
![img_20190114_102621](https://user-images.githubusercontent.com/17840440/51094403-8d7a5680-17e7-11e9-99ba-ac404e743459.png)
![img_20190114_102558](https://user-images.githubusercontent.com/17840440/51094404-8d7a5680-17e7-11e9-800b-be8220ada7b3.png)

**Comment by Loren1994** [comment]
Pad适配可能会有问题,可以用自己的弹框适配
下载没反应的话需要确认几个问题:
1.是否注册网络,存储等权限
2.下载的url是否可用

**Comment by qq237398825** [comment]
您好，我仔细检查了，网络等权限已添加上去。换在手机上测试适配正常，不强制时更新正常，但设置为true还是图二的样子

**Comment by Loren1994** [comment]
感谢您的反馈,目前没有Pad去做适配测试,下一版本会适配一下pad

**Comment by Loren1994** [comment]
https://github.com/Loren1994/AndroidUpdate/blob/master/update/src/main/res/layout/update_dialog_layout.xml#L36
问题为这里写死了高度

**Comment by qq237398825** [comment]
谢谢你告诉。

**Comment by Loren1994** [comment]
已修改,请升级至2.0.1.
