### ISSUE TITLE
【华为畅享受7】Only the original thread that created a view hierarchy can touch its views

### ISSUE THREAD

**Issue by haoxiaocong** [Loren1994/AndroidUpdate#5]
DownloadService中
UpdateDialog.setForceUpdateDialogProcess(progress);
在部分机型中会报
Only the original thread that created a view hierarchy can touch its views错误

改为在主线程中更新即可解决

**Comment by Loren1994** [comment]
需要放在UI线程:-)
建议升级最新版.

**Comment by Loren1994** [comment]
已修复.请升级到2.0.2.
